const FETCH_POSTS = "FETCH_POSTS"
const SET_POSTS = "SET_POSTS"
const TOGGLE_LOADER = "TOGGLE_LOADER"
const FETCH_COMMENTS = "FETCH_COMMENTS"
const SET_COMMENTS = "SET_COMMENTS"

export const postsActions = {
  FETCH_POSTS,
  SET_POSTS,
  TOGGLE_LOADER,
  FETCH_COMMENTS,
  SET_COMMENTS,
}
